[package]
name = "jammars"
version = "0.1.0"
edition = "2021"

[dependencies]
macros = { path = "./proc-macros" }
rand = "0.8"
wyrand = "0.2"

[dev-dependencies]
terminal_size = "0.4"

[features]
seeded = []