[package]
name = "jammars"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "*"
macros = { path = "./macros" }
ndarray = "0.16"
rand = "0.8"
rand_chacha = "0.3"

[features]
colors = []
seeded = []